# Generated by Django 4.2.7 on 2025-08-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answers', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='roomparticipant',
            old_name='completed',
            new_name='is_host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='allow_retakes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='room',
            name='document_text',
        ),
        migrations.RemoveField(
            model_name='room',
            name='show_correct_answers',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='roomquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='room',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Number of attempts allowed (1 for single attempt)'),
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, help_text='Password for the room', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='password_protected',
            field=models.BooleanField(default=False, help_text='Is the room password protected?'),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_enabled',
            field=models.BooleanField(default=False, help_text='Is the timer enabled for this quiz?'),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_type',
            field=models.CharField(choices=[('per_question', 'Per Question'), ('global', 'Global')], default='per_question', help_text='Timer type: per question or global', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_value',
            field=models.IntegerField(default=30, help_text='Time in seconds (per question or global)'),
        ),
        migrations.AddField(
            model_name='roomquestion',
            name='correct_answers',
            field=models.JSONField(default=list, help_text='List of correct answers'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='randomize_options',
            field=models.BooleanField(default=True, help_text='Shuffle answer options for each question'),
        ),
        migrations.AlterField(
            model_name='room',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Shuffle question order for each participant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(db_index=True, help_text='Unique 6-digit code for joining the room', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(help_text='Title of the quiz room', max_length=200),
        ),
        migrations.AlterField(
            model_name='roomquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options for multiple choice or true/false'),
        ),
        migrations.AlterField(
            model_name='roomquestion',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the question in the quiz'),
        ),
        migrations.AlterField(
            model_name='roomquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_in_blank', 'Fill in the Blank')], max_length=20),
        ),
        migrations.DeleteModel(
            name='RoomAnswer',
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rooms.roomparticipant'),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='participantanswer',
            unique_together={('participant', 'question')},
        ),
    ]
