# Generated by Django 4.2.7 on 2025-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_participantanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for this participant in the room', max_length=100),
        ),
    ]
