# Generated by Django 4.2.7 on 2025-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomparticipant_display_name'),
    ]

    operations = [
    ]
